### ISSUE TITLE
non-steamworks dedicated server crowdcontrol mod crash

### ISSUE THREAD

**Issue by Lockxish** [DavidF-Dev/Terraria-Crowd-Control#2] opened 2023-02-04 23:38 UTC
![image](https://user-images.githubusercontent.com/85085615/216793805-216caed8-e364-4668-8c40-e679a138ae62.png)

Hey David. Latest update to your Crowd Control mod appears to have broken Dedicated Server functionality where steamworks is disabled. I did some testing and have confirmed that it'll load in the dedicated tmodloader server if I enable Steam Server on tmodloader server start. The instant I disable steam server, it crashes your mod per the attached screenshot.

Not an issue if I'm hosting and playing through tmodloader itself, but becomes an issue if I want to host a dedicated server and play at the same time as steam counts it as trying to play the same game on two different devices if steam server is enabled.

The previous version 1.0.9. loaded fine without steamworks. Not sure what's changed

**Comment by DavidF-Dev** [comment] 2023-02-05 00:24
Thank you for submitting this issue. I'm currently looking into it. 

Could you let me know how to start a dedicated with Steamworks disabled? I have launched ``start-tModLoaderServer.bat`` and inputted ``n`` so that it doesn't use Steam servers. Is there a step I'm missing?

Thanks.

**Comment by Lockxish** [comment] 2023-02-05 03:44
that's how I was doing it. I fully redownloaded the mod too and tried before submitting the issue.

**Comment by DavidF-Dev** [comment] 2023-02-05 04:41
I see. Unfortunately I am unable to replicate the issue you're having. However I may have a fix.
Are you able to get in contact with me on Discord (``davidfdev#8262``) so I can send a custom build of the mod (GitHub won't let me attach it here).

When you receive the build can you: unsubscribe from the workshop, ensure the mod is uninstalled, then place the provided file in your mods folder (``My Documents/My Games/Terraria/tModLoader/Mods/``), ensure the mod is installed in-game.
Finally, start the dedicated server as you normally would and check if the issue still occurs.

Thanks.

**Comment by DavidF-Dev** [comment] 2023-02-14 05:15
Closing issue. Cannot reproduce.

**Closed as completed** 2023-02-14 05:16 UTC
Labels: bug
